#!/usr/bin/python3

import sys, time

def recursive_fibonacci(n):
  if n < 1:
    return 0
  elif n == 1:
    return 1
  else:
    return recursive_fibonacci(n - 1) + recursive_fibonacci(n - 2)

n = int(sys.argv[1])
print(n)

start = time.time()
print(recursive_fibonacci(n))
print(int(time.time() - start) * 1000)
