#!/usr/bin/php
<?php

function recursiveFibonacci($n) {
  if ($n < 1)
    return 0;
  elseif ($n == 1)
    return 1;
  else
    return recursiveFibonacci($n - 1) + recursiveFibonacci($n - 2);
}

$n = (int)$argv[1];
echo "$n\n";

$start = microtime(true);
echo recursiveFibonacci($n), "\n";
echo (int)((microtime(true) - $start) * 1000), "\n";

?>
